language: c

before_install:
  - sudo apt update
  - sudo apt dist-upgrade -y
  - sudo do-release-upgrade -y
  - sudo apt update
  - sudo apt install -y valac valac libgee-0.8-dev libarchive-dev libgirepository1.0-dev gobject-introspection meson ninja-build

script:
  - mkdir build
  - cd build
  - meson ..
  - ninja
